spring.application.name=AIVoiceAssistant
spring.config.import=optional:file:.env[.properties]

yandex.speechkit.api-url=https://tts.api.cloud.yandex.net/speech/v1/tts:synthesize

spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.api-key=${OPENROUTER_API_KEY}
spring.ai.openai.chat.model=liquid/lfm-2.5-2.6b:free

spring.ai.openai.chat.max-completion-tokens=512
spring.ai.openai.timeout=30s
spring.ai.openai.max-retries=2
